# -*- coding: utf-8 -*-
"""brain-turm.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/181vHqsFf7zvKZ0aAT80xUwF-kYAYFDix
"""

!pip install ultralytics

import torch
import matplotlib.pyplot as plt
import numpy as np
import cv2

from ultralytics import YOLO

model = YOLO('yolov10l.pt')

model.train(data = '/content/drive/MyDrive/archive/axial_t1wce_2_class/axial_t1wce_2_class.yaml', epochs = 60, imgsz = 320, device='0')

yaml_content = """
path: ../content/drive/MyDrive/archive
train: /content/drive/MyDrive/archive/axial_t1wce_2_class/images/train
val: /content/drive/MyDrive/archive/axial_t1wce_2_class/images/test

# Classes
nc: 2
names: ['negative','positive']
"""

# Write to dataset.yml (overwrite old file)
with open('/content/drive/MyDrive/archive/axial_t1wce_2_class/axial_t1wce_2_class.yaml', 'w') as f:
    f.write(yaml_content)

model1 = YOLO('yolov10l.pt')

model1.train(data = '/content/drive/MyDrive/archive/coronal_t1wce_2_class/coronal_t1wce_2_class.yaml', epochs = 60, imgsz = 320, device='0')

yaml_content = """
path: ../content/drive/MyDrive/archive
train: /content/drive/MyDrive/archive/coronal_t1wce_2_class/images/train
val:  /content/drive/MyDrive/archive/coronal_t1wce_2_class/images/test

# Classes
nc: 2
names: ['negative','positive']
"""

# Write to dataset.yml (overwrite old file)
with open('/content/drive/MyDrive/archive/coronal_t1wce_2_class/coronal_t1wce_2_class.yaml', 'w') as f:
    f.write(yaml_content)

model2 = YOLO('yolov10l.pt')

model2.train(data = '/content/drive/MyDrive/archive/sagittal_t1wce_2_class/sagittal_t1wce_2_class.yaml', epochs = 60, imgsz = 320, device='0')

yaml_content = """
path: ../content/drive/MyDrive/archive
train: /content/drive/MyDrive/archive/sagittal_t1wce_2_class/images/train
val:  /content/drive/MyDrive/archive/sagittal_t1wce_2_class/images/test

# Classes
nc: 2
names: ['negative','positive']
"""

# Write to dataset.yml (overwrite old file)
with open('/content/drive/MyDrive/archive/sagittal_t1wce_2_class/sagittal_t1wce_2_class.yaml', 'w') as f:
    f.write(yaml_content)

from ultralytics import YOLO

model = YOLO('/content/runs/detect/train/weights/best.pt')

results = model('/content/drive/MyDrive/archive/axial_t1wce_2_class/images/test')
results[74].show()

from ultralytics import YOLO

model1 = YOLO('/content/runs/detect/train/weights/best.pt')

results = model1('/content/drive/MyDrive/archive/coronal_t1wce_2_class/images/test')
for i in range(0, 74):
    results[i].show()
    print()
    print("*"*67)
    print()

from ultralytics import YOLO

model1 = YOLO('/content/runs/detect/train/weights/best.pt')

results = model2('/content/drive/MyDrive/archive/sagittal_t1wce_2_class/images/test')
for i in range(0, 69):
    results[i].show()
    print()
    print("*"*67)
    print()